//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWebAPIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCity
    {
        public int CityID { get; set; }
        public Nullable<int> CountyID { get; set; }
        public string CityName { get; set; }
    
        public virtual tblCountry tblCountry { get; set; }
    }
}
