//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherWebAPIService
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTemperature
    {
        public int CityID { get; set; }
        public string Location { get; set; }
        public Nullable<System.DateTime> Time { get; set; }
        public Nullable<int> Visibility { get; set; }
        public string SkyCondition { get; set; }
        public Nullable<decimal> Temperature { get; set; }
        public Nullable<int> DewPoint { get; set; }
        public Nullable<int> RelativeHumidity { get; set; }
        public Nullable<int> Preasure { get; set; }
    }
}
